<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Laphar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mlaphar');
    } 

    /*
     * Listing of laphar
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('laphar/index?');
        $config['total_rows'] = $this->Mlaphar->get_all_laphar_count();
        $this->pagination->initialize($config);

        $data['laphar'] = $this->Mlaphar->get_all_laphar($params);
        
        $data['_view'] = 'laphar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new laphar
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('laphar','Laphar','max_length[1000]|min_length[10]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'time' => date('Y-m-d H:i:s'),
				'satuan' => $this->session->userdata('satuan'),
				'laphar' => $this->input->post('laphar'),
            );
            
            $laphar_id = $this->Mlaphar->add_laphar($params);
            $this->session->set_flashdata('msg','simpan');
            redirect(base_url('admin/inputlaphar'));
        }
        else
        {            
            $this->session->set_flashdata('msg','gagal');
            redirect(base_url('admin/inputlaphar'));
        }
    }  

    /*
     * Editing a laphar
     */
    function edit($id)
    {   
        // check if the laphar exists before trying to edit it
        $data['laphar'] = $this->Mlaphar->get_laphar($id);
        
        if(isset($data['laphar']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('laphar','Laphar','max_length[1000]|min_length[10]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'time' => $this->input->post('time'),
					'satuan' => $this->input->post('satuan'),
					'laphar' => $this->input->post('laphar'),
                );

                $this->Mlaphar->update_laphar($id,$params);            
                redirect('laphar/index');
            }
            else
            {
                $data['_view'] = 'laphar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The laphar you are trying to edit does not exist.');
    } 

    /*
     * Deleting laphar
     */
    function remove($id)
    {
        $laphar = $this->Mlaphar->get_laphar($id);

        // check if the laphar exists before trying to delete it
        if(isset($laphar['id']))
        {
            $this->Mlaphar->delete_laphar($id);
            redirect('laphar/index');
        }
        else
            show_error('The laphar you are trying to delete does not exist.');
    }
    
}
