<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Minstagram extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get instagram by id
     */
    function get_instagram($id)
    {
        return $this->db->get_where('instagram',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all instagram
     */
    function get_all_instagram()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('instagram')->result_array();
    }
        
    /*
     * function to add new instagram
     */
    function add_instagram($data)
    {
        return $this->db->insert_batch('instagram', $data);
    }
    
    /*
     * function to update instagram
     */
    function update_instagram($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('instagram',$params);
    }
    
    /*
     * function to delete instagram
     */
    function delete_instagram($id)
    {
        return $this->db->delete('instagram',array('id'=>$id));
    }
}
