<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mtwitter extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get twitter by id
     */
    function get_twitter($id)
    {
        return $this->db->get_where('twitter',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all twitter
     */
    function get_all_twitter()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('twitter')->result_array();
    }
        
    /*
     * function to add new twitter
     */
    function add_twitter($data)
    {
        return $this->db->insert_batch('twitter', $data);
    }
    
    /*
     * function to update twitter
     */
    function update_twitter($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('twitter',$params);
    }
    
    /*
     * function to delete twitter
     */
    function delete_twitter($id)
    {
        return $this->db->delete('twitter',array('id'=>$id));
    }
}
